{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wordpress-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  mysql-root-password: {{ .Values.secrets.mysql.rootPassword | b64enc }}
  mysql-password: {{ .Values.secrets.mysql.password | b64enc }}
  mysql-user: {{ .Values.secrets.mysql.user | b64enc }}
  mysql-database: {{ .Values.secrets.mysql.database | b64enc }}
{{- end }}