apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: {{ .Release.Name }}
    tier: frontend
  {{- if .Values.wordpress.service.annotations }}
  annotations:
    {{- toYaml .Values.wordpress.service.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.wordpress.service.port }}
    targetPort: {{ .Values.wordpress.service.port }}
  selector:
    app: {{ .Release.Name }}
    tier: frontend
  type: {{ .Values.wordpress.service.type }}